"""Provider-agnostic LLM interface for the PRAgent ReAct loop.

Each concrete provider (Gemini, Claude, …) subclasses LLMProvider and
manages its own conversation state.  The orchestrator never touches
provider-specific SDKs — it only works with LLMResponse, ToolCall, and
ToolResult.
"""

from __future__ import annotations

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from typing import Any


@dataclass
class ToolCall:
    """A tool call the model wants to make."""

    id: str          # unique ID for matching tool results; generated by provider
    name: str
    args: dict[str, Any]


@dataclass
class ToolResult:
    """The result of executing a tool call."""

    call_id: str     # matches ToolCall.id
    name: str
    content: str


@dataclass
class LLMResponse:
    """Normalized response from any LLM provider."""

    text: str | None = None
    tool_calls: list[ToolCall] = field(default_factory=list)

    @property
    def has_tool_calls(self) -> bool:
        return bool(self.tool_calls)


class LLMProvider(ABC):
    """Abstract base for an LLM provider driving the PRAgent ReAct loop.

    Each instance manages its own conversation state (message history,
    tool declarations) so the orchestrator stays provider-agnostic.
    """

    @abstractmethod
    async def start(
        self,
        *,
        system_prompt: str,
        tools: list[dict[str, Any]],  # MCP-format dicts: {name, description, parameters}
        first_message: str,
    ) -> LLMResponse:
        """Begin a new review conversation with the first user message."""

    @abstractmethod
    async def submit_tool_results(
        self,
        results: list[ToolResult],
    ) -> LLMResponse:
        """Continue the conversation after executing one or more tool calls."""

    @abstractmethod
    async def continue_after_thought(self) -> LLMResponse:
        """Continue the conversation after a THOUGHT text response.

        Some providers (Claude) require a user turn after every assistant
        message.  This method inserts the necessary continuation turn
        internally so the orchestrator loop stays uniform.
        """

    @abstractmethod
    async def generate_no_tools(self, message: str) -> LLMResponse:
        """Send a user message with tool-calling disabled.

        Used for RETRY_MALFORMED_JSON and FORCE_CONCLUDE prompts where we
        only want plain text back.
        """

    @property
    @abstractmethod
    def tool_names(self) -> set[str]:
        """Names of all tools declared to this provider instance."""
