import type {
  Review,
  DashboardStats,
  AgentLog,
  ReviewComment,
} from "./types";

export const mockStats: DashboardStats = {
  total_reviews: 1247,
  critical_issues: 89,
  prs_this_week: 43,
  avg_review_time: "4.2m",
};

export const mockReviews: Review[] = [
  {
    id: 1,
    repo_id: 1,
    pr_number: 142,
    pr_title: "Add exam project function/creativiti...",
    status: "completed",
    total_comments: 5,
    critical_count: 2,
    warning_count: 2,
    info_count: 1,
    created_at: "2024-05-29T12:05:39Z",
    repo: { id: 1, user_id: 1, full_name: "JetBrains Mono", webhook_id: null, created_at: "" },
  },
  {
    id: 2,
    repo_id: 1,
    pr_number: 156,
    pr_title: "Add exam project features/naleterly...",
    status: "reviewing",
    total_comments: 4,
    critical_count: 1,
    warning_count: 2,
    info_count: 1,
    created_at: "2024-05-29T13:20:05Z",
    repo: { id: 1, user_id: 1, full_name: "JetBrains Mono", webhook_id: null, created_at: "" },
  },
  {
    id: 3,
    repo_id: 1,
    pr_number: 89,
    pr_title: "Add exam project function/mmremti...",
    status: "failed",
    total_comments: 0,
    critical_count: 0,
    warning_count: 0,
    info_count: 0,
    created_at: "2024-05-29T13:09:05Z",
    repo: { id: 1, user_id: 1, full_name: "JetBrains Mono", webhook_id: null, created_at: "" },
  },
  {
    id: 4,
    repo_id: 1,
    pr_number: 201,
    pr_title: "Add exam project features/naictarly...",
    status: "reviewing",
    total_comments: 2,
    critical_count: 0,
    warning_count: 1,
    info_count: 1,
    created_at: "2024-06-29T13:20:36Z",
    repo: { id: 1, user_id: 1, full_name: "JetBrains Mono", webhook_id: null, created_at: "" },
  },
  {
    id: 5,
    repo_id: 2,
    pr_number: 34,
    pr_title: "Fix authentication middleware bypass",
    status: "completed",
    total_comments: 8,
    critical_count: 3,
    warning_count: 3,
    info_count: 2,
    created_at: "2024-06-15T09:45:12Z",
    repo: { id: 2, user_id: 1, full_name: "acme/web-app", webhook_id: null, created_at: "" },
  },
  {
    id: 6,
    repo_id: 3,
    pr_number: 78,
    pr_title: "Refactor database connection pooling",
    status: "completed",
    total_comments: 3,
    critical_count: 0,
    warning_count: 2,
    info_count: 1,
    created_at: "2024-06-20T16:30:00Z",
    repo: { id: 3, user_id: 1, full_name: "acme/api-server", webhook_id: null, created_at: "" },
  },
  {
    id: 7,
    repo_id: 2,
    pr_number: 45,
    pr_title: "Add rate limiting to public endpoints",
    status: "pending",
    total_comments: 0,
    critical_count: 0,
    warning_count: 0,
    info_count: 0,
    created_at: "2024-07-01T08:15:22Z",
    repo: { id: 2, user_id: 1, full_name: "acme/web-app", webhook_id: null, created_at: "" },
  },
];

export const mockAgentLogs: AgentLog[] = [
  {
    id: 1, review_id: 1, event_type: "thinking",
    content: "Analyzing PR #142: Add exam project function. Let me start by reading the PR details and diff.",
    created_at: "2024-05-29T12:04:00Z",
  },
  {
    id: 2, review_id: 1, event_type: "fetching",
    content: "Calling pull_request_read(method: 'get', owner: 'jetbrains', repo: 'mono', pull_number: 142)",
    created_at: "2024-05-29T12:04:02Z",
  },
  {
    id: 3, review_id: 1, event_type: "fetching",
    content: "Calling pull_request_read(method: 'get_diff', owner: 'jetbrains', repo: 'mono', pull_number: 142)",
    created_at: "2024-05-29T12:04:05Z",
  },
  {
    id: 4, review_id: 1, event_type: "thinking",
    content: "The PR adds a new exam project function. I can see changes in 3 files: src/exam.py, tests/test_exam.py, and config.yaml. Let me examine each file for security, bugs, and code quality issues.",
    created_at: "2024-05-29T12:04:08Z",
  },
  {
    id: 5, review_id: 1, event_type: "fetching",
    content: "Calling get_file_contents(owner: 'jetbrains', repo: 'mono', path: 'src/exam.py', ref: 'feature/creativiti')",
    created_at: "2024-05-29T12:04:10Z",
  },
  {
    id: 6, review_id: 1, event_type: "found",
    content: "CRITICAL: SQL injection vulnerability in src/exam.py line 45 — user input is directly interpolated into SQL query without parameterization.",
    created_at: "2024-05-29T12:04:15Z",
  },
  {
    id: 7, review_id: 1, event_type: "found",
    content: "WARNING: Missing error handling in src/exam.py line 67 — database connection failure would cause unhandled exception.",
    created_at: "2024-05-29T12:04:18Z",
  },
  {
    id: 8, review_id: 1, event_type: "fetching",
    content: "Calling get_repository_tree(owner: 'jetbrains', repo: 'mono', ref: 'main', path: 'tests/')",
    created_at: "2024-05-29T12:04:20Z",
  },
  {
    id: 9, review_id: 1, event_type: "found",
    content: "WARNING: Test coverage gap — new function create_exam() has no corresponding test case in tests/test_exam.py.",
    created_at: "2024-05-29T12:04:25Z",
  },
  {
    id: 10, review_id: 1, event_type: "posting",
    content: "Creating pending review with 5 inline comments...",
    created_at: "2024-05-29T12:05:00Z",
  },
  {
    id: 11, review_id: 1, event_type: "posting",
    content: "Submitting review with REQUEST_CHANGES verdict (2 critical issues found).",
    created_at: "2024-05-29T12:05:30Z",
  },
  {
    id: 12, review_id: 1, event_type: "done",
    content: "Review complete. Found 5 issues: 2 critical, 2 warnings, 1 info.",
    created_at: "2024-05-29T12:05:39Z",
  },
];

export const mockReviewComments: ReviewComment[] = [
  {
    id: 1, review_id: 1, file_path: "src/exam.py", line_number: 45,
    category: "security", severity: "critical",
    body: "SQL injection vulnerability: user input is directly interpolated into the SQL query. Use parameterized queries instead.",
    fix_suggestion: 'cursor.execute("SELECT * FROM exams WHERE id = %s", (exam_id,))',
    created_at: "2024-05-29T12:05:10Z",
  },
  {
    id: 2, review_id: 1, file_path: "src/exam.py", line_number: 52,
    category: "security", severity: "critical",
    body: "Sensitive data exposure: exam answers are logged to stdout in debug mode. This could leak to production logs.",
    fix_suggestion: "Use logger.debug() with a flag check, and never log answer content directly.",
    created_at: "2024-05-29T12:05:12Z",
  },
  {
    id: 3, review_id: 1, file_path: "src/exam.py", line_number: 67,
    category: "error_handling", severity: "warning",
    body: "Missing error handling: database connection failure would cause an unhandled exception and crash the service.",
    fix_suggestion: "Wrap the database call in a try/except block and handle ConnectionError gracefully.",
    created_at: "2024-05-29T12:05:15Z",
  },
  {
    id: 4, review_id: 1, file_path: "tests/test_exam.py", line_number: 1,
    category: "test_coverage", severity: "warning",
    body: "Test coverage gap: the new create_exam() function has no corresponding test case.",
    fix_suggestion: "Add test_create_exam() with both valid and invalid input scenarios.",
    created_at: "2024-05-29T12:05:18Z",
  },
  {
    id: 5, review_id: 1, file_path: "config.yaml", line_number: 12,
    category: "code_quality", severity: "info",
    body: "The timeout value is hardcoded. Consider making this configurable via environment variable.",
    fix_suggestion: "timeout: ${EXAM_TIMEOUT:-30}",
    created_at: "2024-05-29T12:05:20Z",
  },
];
